# Generated by Django 4.2.1 on 2023-05-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите название тега', max_length=200, verbose_name='Название')),
                ('color', models.CharField(blank=True, help_text='введите цвет тега (HEX)', max_length=16, verbose_name='Цвет')),
                ('slug', models.SlugField(blank=True, help_text='введите уникальный слаг', max_length=200, unique=True, verbose_name='адрес')),
            ],
        ),
    ]
