# Generated by Django 4.2.1 on 2023-06-08 08:47

from django.db import migrations, models
import tags.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tags_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(help_text='введите цвет тега (HEX)', max_length=16, validators=[tags.validators.HexValidator()], verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(help_text='введите уникальный слаг', max_length=200, unique=True, verbose_name='адрес'),
        ),
    ]
