# Generated by Django 4.2.1 on 2023-06-10 16:10

from django.db import migrations, models
import tags.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_alter_tags_name_alter_tags_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(help_text='введите цвет тега (HEX)', max_length=7, validators=[tags.validators.HexValidator()], verbose_name='Цвет'),
        ),
    ]
