# Generated by Django 4.2.1 on 2023-06-12 07:54

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_alter_tags_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(help_text='введите название тега', max_length=200, validators=[users.validators.FirstLastnameValidator()], verbose_name='Название'),
        ),
    ]
