# Generated by Django 4.2.1 on 2023-06-12 21:06

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_alter_tags_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(help_text='введите название тега', max_length=200, unique=True, validators=[users.validators.FirstLastnameValidator()], verbose_name='Название'),
        ),
        migrations.AddConstraint(
            model_name='tags',
            constraint=models.UniqueConstraint(fields=('name', 'color'), name='unique_name_color'),
        ),
    ]
