# Generated by Django 4.2.1 on 2023-05-16 20:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0001_initial'),
        ('tags', '0002_alter_tags_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientsToRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'минимальное значение 1')])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorited', models.BooleanField()),
                ('is_in_shopping_cart', models.BooleanField()),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/photos/%Y%M%d/')),
                ('text', models.TextField(help_text='введите описание', verbose_name='описание')),
                ('cooking_time', models.IntegerField(help_text='введите время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1, 'минимальное значение 1')], verbose_name='время приготовления в минутах ')),
                ('author', models.ForeignKey(help_text='Автор рецепта', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='автор рецепта')),
                ('ingredients', models.ManyToManyField(through='recipes.IngredientsToRecipes', to='ingredients.ingredient')),
                ('tags', models.ManyToManyField(help_text='добавьте тег рецепта', null=True, related_name='recipes', to='tags.tags', verbose_name='тег рецепта')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientstorecipes',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes'),
        ),
    ]
