# Generated by Django 4.2.1 on 2023-05-17 20:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0002_alter_tags_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('measurement_unit', models.CharField(max_length=200, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Игридиент',
                'verbose_name_plural': 'Игридиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='IngredientsToRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Введите количество минимальное значение 1', validators=[django.core.validators.MinValueValidator(1, 'минимальное значение 1')], verbose_name='количество')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
            ],
            options={
                'verbose_name': 'Ингридиенты к рецептам',
                'verbose_name_plural': 'Ингридиенты',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='добавьте название блюда', max_length=200, verbose_name='Название')),
                ('is_favorited', models.BooleanField(help_text='добавить в избраное', verbose_name='Избранное')),
                ('is_in_shopping_cart', models.BooleanField(help_text='добавить в корзину покупок', verbose_name='Корзина')),
                ('image', models.ImageField(upload_to='media/photos/%Y%M%d/')),
                ('text', models.TextField(help_text='введите описание', verbose_name='описание')),
                ('cooking_time', models.IntegerField(help_text='введите время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1, 'минимальное значение 1')], verbose_name='время приготовления в минутах ')),
                ('author', models.ForeignKey(help_text='Автор рецепта', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='автор рецепта')),
                ('ingredients', models.ManyToManyField(related_name='recipes', through='recipes.IngredientsToRecipes', to='recipes.ingredient')),
                ('tags', models.ManyToManyField(help_text='добавьте тег рецепта', null=True, related_name='recipes', to='tags.tags', verbose_name='тег рецепта')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='ingredientstorecipes',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes'),
        ),
    ]
