# Generated by Django 4.2.1 on 2023-05-18 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',), 'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Игридиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientstorecipes',
            options={'verbose_name': 'Ингридиенты к рецептам', 'verbose_name_plural': 'Ингридиенты к рецептам'},
        ),
        migrations.CreateModel(
            name='Favorited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorited', models.BooleanField(default=False, verbose_name='В избранном ?')),
                ('recipes', models.ForeignKey(help_text='добавьте рецепт в избранном', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited', to='recipes.recipes', verbose_name='рецепт в избранном')),
                ('user', models.ForeignKey(help_text='добавьте рецепт в избранном', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited', to=settings.AUTH_USER_MODEL, verbose_name='рецепт в избранном')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.AddConstraint(
            model_name='favorited',
            constraint=models.UniqueConstraint(fields=('user', 'recipes'), name='unique_favorited'),
        ),
    ]
