# Generated by Django 4.2.1 on 2023-05-18 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorited',
            name='recipes',
            field=models.ForeignKey(help_text='добавьте рецепт в корзину', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoppingcart', to='recipes.recipes', verbose_name='рецепт в корзине'),
        ),
        migrations.AlterField(
            model_name='favorited',
            name='user',
            field=models.ForeignKey(help_text='добавьте рецепт в корзину', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoppingcart', to=settings.AUTH_USER_MODEL, verbose_name='рецепт в корзине'),
        ),
    ]
