# Generated by Django 4.2.1 on 2023-05-29 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_alter_favorited_recipes_alter_favorited_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_shopping_cart', models.BooleanField(default=False, verbose_name='В корзине ?')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
        migrations.AlterModelOptions(
            name='favorited',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='favorited',
            name='unique_favorited',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='is_in_shopping_cart',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='recipes',
            field=models.ForeignKey(help_text='добавлен рецепт в корзину', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoppingcart', to='recipes.recipes', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(help_text='Кто добавляет рецепт в корзину', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoppingcart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipes'), name='unique_favorited'),
        ),
    ]
