# Generated by Django 4.2.1 on 2023-05-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_shoppingcart_alter_favorited_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorited',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_favorited',
        ),
        migrations.AddConstraint(
            model_name='favorited',
            constraint=models.UniqueConstraint(fields=('user', 'recipes'), name='unique_favorited'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipes'), name='unique_shoppingcart'),
        ),
    ]
