# Generated by Django 4.2.1 on 2023-06-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tags_options'),
        ('recipes', '0006_alter_favorited_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(help_text='добавьте тег рецепта', null=True, related_name='recipes_tag', to='tags.tags', verbose_name='тег рецепта'),
        ),
    ]
