# Generated by Django 4.2.1 on 2023-06-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tags_options'),
        ('recipes', '0007_alter_recipes_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(help_text='добавьте тег рецепта', null=True, to='tags.tags', verbose_name='тег рецепта'),
        ),
    ]
