# Generated by Django 4.2.1 on 2023-06-08 13:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipes_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorited',
            name='recipes',
            field=models.ForeignKey(help_text='добавьте рецепт в избранном', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recipes.recipes', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, validators=[recipes.validators.NameValidator()], verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='ingredientstorecipes',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recipes.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='введите время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1, 'минимальное значение 1')], verbose_name='время приготовления в минутах '),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipes',
            field=models.ForeignKey(help_text='добавлен рецепт в корзину', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recipes.recipes', verbose_name='Рецепт'),
        ),
    ]
