# Generated by Django 4.2.1 on 2023-06-08 13:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_favorited_recipes_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, validators=[recipes.validators.NameValidator()], verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='ingredientstorecipes',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, help_text='Введите количество минимальное значение 1', validators=[django.core.validators.MinValueValidator(1, 'минимальное значение 1')], verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='ingredientstorecipes',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_amount', to='recipes.recipes'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_ingredient'),
        ),
    ]
