# Generated by Django 4.2.1 on 2023-06-10 16:10

from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_recipes_ingredients_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, validators=[users.validators.FirstLastnameValidator()], verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='ingredientstorecipes',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipes'),
        ),
    ]
