# Generated by Django 4.2.1 on 2023-06-12 11:38

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_remove_favorited_is_favorited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(help_text='добавьте название блюда', max_length=200, validators=[users.validators.FirstLastnameValidator()], verbose_name='Название'),
        ),
    ]
