# Generated by Django 4.2.1 on 2023-06-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_alter_tags_name_tags_unique_name_color'),
        ('recipes', '0014_remove_favorited_unique_favorited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(help_text='добавьте тег рецепта', to='tags.tags', verbose_name='тег рецепта'),
        ),
    ]
