# Generated by Django 4.2.1 on 2023-05-24 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_follow_options_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='users.Follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='author',
            field=models.ForeignKey(help_text='Тот на кого подписались', on_delete=django.db.models.deletion.CASCADE, related_name='to_following', to=settings.AUTH_USER_MODEL, verbose_name='Кумир'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(help_text='Тот кто подписался', on_delete=django.db.models.deletion.CASCADE, related_name='from_follower', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
    ]
